package com.haderacher.bcbackend.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.proxy.HibernateProxy;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

@Entity
@Table(name = "job")
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Job {
    // Use UUID generated by Hibernate
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "name", nullable = false)
    @NotBlank
    private String name;

    @Column(name = "description", columnDefinition = "TEXT", nullable = false)
    @NotBlank
    private String description;

    /**
     * (废弃) 公司字段，保留以兼容历史数据
     */
    @Deprecated
    @Column(name = "company")
    private String company;

    @Column(name = "recruiter", nullable = false)
    @NotBlank
    private String recruiter;

    @Column(name = "address", nullable = false)
    @NotBlank
    private String address;

    @Column(name = "degree_req", nullable = false)
    @NotBlank
    private String degreeReq;

    @Column(name = "salary_min", nullable = false)
    @NotNull
    private Integer salaryMin;

    @Column(name = "salary_max")
    private Integer salaryMax;

    @Column(name = "salary_type")
    private String salaryType;

    @Column(name = "salary_annual")
    private Integer salaryAnnual;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "job_labels", joinColumns = @JoinColumn(name = "job_id"))
    @Column(name = "label")
    @NotNull
    @Builder.Default
    private List<String> labels = new ArrayList<>();

    @Column(name = "category", nullable = false)
    @NotBlank
    private String category;

    @Override
    public final boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        Job job = (Job) o;
        return getId() != null && Objects.equals(getId(), job.getId());
    }

    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }
}
